-- =========================================================================
-- NISTULA UNIFIED MESSAGING PLATFORM SCHEMA (Updated)
-- =========================================================================

-- 1. GUESTS (deduplication across channels)
CREATE TABLE guests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255) UNIQUE,
  phone VARCHAR(20),
  name VARCHAR(255) NOT NULL,
  source_first_contact VARCHAR(50),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 2. PROPERTIES (Villa B1, etc.)
CREATE TABLE properties (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  bedrooms INT,
  max_guests INT,
  base_rate_inr INT,
  extra_guest_rate_inr INT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 3. MESSAGES (all inbound)
CREATE TABLE messages (
  id UUID PRIMARY KEY,
  guest_id UUID REFERENCES guests(id),
  property_id VARCHAR(50) REFERENCES properties(id),
  source VARCHAR(50) NOT NULL,
  source_message_id VARCHAR(255) UNIQUE,
  message_text TEXT NOT NULL,
  query_type VARCHAR(50),
  booking_ref VARCHAR(100),
  timestamp TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 4. AI_RESPONSES (draft tracking)
CREATE TABLE ai_responses (
  id UUID PRIMARY KEY,
  message_id UUID REFERENCES messages(id) UNIQUE,
  drafted_reply TEXT NOT NULL,
  confidence_score DECIMAL(3,2),
  action VARCHAR(50),
  agent_edited BOOLEAN DEFAULT FALSE,
  final_reply TEXT,
  was_auto_sent BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 5. CONVERSATIONS (thread linking)
CREATE TABLE conversations (
  id UUID PRIMARY KEY,
  guest_id UUID REFERENCES guests(id),
  property_id VARCHAR(50) REFERENCES properties(id),
  booking_ref VARCHAR(100),
  status VARCHAR(50) DEFAULT 'active',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(guest_id, property_id, booking_ref)
);

-- =========================================================================
-- DESIGN RATIONALE
-- =========================================================================
-- 
-- Why these 5 tables?
-- These tables separate the core entities of the system:
-- - Guests: Who is messaging.
-- - Properties: What they are messaging about.
-- - Messages: The actual content.
-- - AI Responses: The drafts generated by Claude, separated to allow auditing and editing.
-- - Conversations: Groups messages by guest and property/booking context.
--
-- Normalization level (3NF, why not higher?)
-- The schema is in 3NF (Third Normal Form). All fields depend directly on the primary key.
-- We don't normalize further (like splitting address from property) because it would add 
-- unnecessary join complexity for a simple assessment.
--
-- Deduplication strategy for guests
-- Guests are deduplicated by `email` (UNIQUE constraint). In a real system, we would also 
-- check phone numbers or use fuzzy matching, but email uniqueness is a solid baseline.
--
-- How AI responses are audited
-- The `ai_responses` table links 1:1 with `messages`. It stores the `drafted_reply` (original AI output), 
-- `agent_edited` (boolean flag), and `final_reply` (what was actually sent). This allows us to compare 
-- AI output vs human edits to improve the prompt over time.

-- =========================================================================
-- INDEXES
-- =========================================================================
CREATE INDEX idx_messages_guest_id ON messages(guest_id);
CREATE INDEX idx_messages_property_id ON messages(property_id);
CREATE INDEX idx_messages_timestamp ON messages(timestamp DESC);
CREATE INDEX idx_messages_booking_ref ON messages(booking_ref);
CREATE INDEX idx_conversations_guest_property ON conversations(guest_id, property_id);
CREATE INDEX idx_ai_responses_message_id ON ai_responses(message_id);
